import Gold from './imgs/gold-unsplash.jpg';

const itemList = [
    {
        'serial': "123456",
        'image': "https://picsum.photos/200",
        "name": "Organic Strawberries",
        "serving": "1.5lb",
        "price": "2.25",
        "quantity": "1",
    },
    {
        'serial': "234567",
        'image': "https://picsum.photos/200",
        "name": "Rural Strawberries",
        "serving": "1.5lb",
        "price": "2.25",
        "quantity": "1",
    }, {
        'serial': "232323",
        'image': "https://picsum.photos/200",
        "name": "Natural Strawberries",
        "serving": "1.5lb",
        "price": "2.25",
        "quantity": "1",
    },
    {
        'serial': "333333",
        'image': "https://picsum.photos/200",
        "name": "Organic Potato",
        "serving": "1.0lb",
        "price": "1.75",
        "quantity": "1",
    },
    {
        'serial': "444444",
        'image': "https://picsum.photos/200",
        "name": "Hawaii Pineapples",
        "serving": "1.0lb",
        "price": "2.25",
        "quantity": "1",
    },
    {
        'serial': "555555",
        'image': "https://picsum.photos/200",
        "name": "Fuji Apples",
        "serving": "1.0lb",
        "price": "2.25",
        "quantity": "1",
    },
    {
        'serial': "666666",
        'image': "https://picsum.photos/200",
        "name": "Premium Rice",
        "serving": "1.0lb",
        "price": "1.75",
        "quantity": "1",
    },
    {
        'serial': "777777",
        'image': "https://picsum.photos/200",
        "name": "Vanilla Icecream",
        "serving": "1.0lb",
        "price": "2.25",
        "quantity": "1",
    },
    {
        'serial': "999999",
        'image': "https://picsum.photos/200",
        "name": "Organic Pet Rabbit Food",
        "serving": "4.5lb",
        "price": "11.29",
        "quantity": "1",
    },
    {
        'serial': "435628",
        'image': "https://picsum.photos/200",
        "name": "Toilet Bleach",
        "serving": "1.0lb",
        "price": "2.25",
        "quantity": "1",
    },
    {
        'serial': "123642",
        'image': "https://picsum.photos/200",
        "name": "Mandarin Orange",
        "serving": "1.0lb",
        "price": "2.25",
        "quantity": "1",
    },
    {
        'serial': "888888",
        'image': "https://picsum.photos/200",
        "name": "Hair Conditioner",
        "serving": "1.0lb",
        "price": "2.25",
        "quantity": "1",
    }, {
        'serial': "154732",
        'image': "https://picsum.photos/200",
        "name": "Watermelon",
        "serving": "1.0lb",
        "price": "2.25",
        "quantity": "1",
    },
    {
        'serial': "686868",
        'image': "https://picsum.photos/200",
        "name": "Farm Squash",
        "serving": "1.0lb",
        "price": "2.25",
        "quantity": "1",
    },
    {
        'serial': "654321",
        'image': Gold,
        "name": "Gold",
        "serving": "1g",
        "price": "30",
        "quantity": "1",
    },
]
export default itemList;